// ============================================================
// PLANET MINER DEV HQ – ALL DATA
// Bearbeite diese Datei um Inhalte zu aendern.
// ============================================================

// --- LOGIN CREDENTIALS ---
// Passwort-Hashes (SHA-256). Zum Aendern: neuen Hash generieren
// via Browser-Konsole: crypto.subtle.digest('SHA-256', new TextEncoder().encode('DEIN_PASSWORT')).then(b => console.log([...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')))
const USERS = {
  hannes: {
    hash: "fbf32482732a420c27dd56fd83ddd42953a26f721478be25d9e4a86eeda91f2a",
    display: "Hannes",
    color: "assignee-hannes",
    initial: "H",
  },
  lamar: {
    hash: "fbf32482732a420c27dd56fd83ddd42953a26f721478be25d9e4a86eeda91f2a",
    display: "Lamar",
    color: "assignee-kumpel",
    initial: "L",
  },
};

// --- GAME INFO ---
const GAME_INFO = {
  title: "Planet Miner",
  subtitle: "Mine. Upgrade. Explore the Universe.",
};

// --- TABS ---
const TABS = [
  { id: "vision",     label: "Vision",         icon: "\uD83C\uDF0C" },
  { id: "tickets",    label: "Tickets",        icon: "\uD83C\uDFAB" },
  { id: "activity",   label: "Activity",       icon: "\uD83D\uDCC8" },
  { id: "systeme",    label: "Systeme",        icon: "\u2699\uFE0F" },
  { id: "wirtschaft", label: "Wirtschaft",     icon: "\uD83D\uDCB0" },
  { id: "roadmap",    label: "Roadmap",        icon: "\uD83D\uDE80" },
  { id: "reise",      label: "Spielerreise",   icon: "\uD83C\uDFAE" },
];

// ============================================================
// TICKETS
// Status: "backlog" | "progress" | "done"
// Priority: "critical" | "high" | "medium" | "low"
// Assignee: username key from USERS or null
// Tags: array of tag keys (mining, pickaxe, ui, audio, world, system, shop, multiplayer, bug, feature, polish)
// ============================================================
// SEED_TICKETS: Used for one-time migration to Firestore.
// After migration, all ticket data lives in Firestore "tickets" collection.
const SEED_TICKETS = [
  // --- BACKLOG: Kurzfristig ---
  {
    id: "PM-003",
    title: "Erz-Groessen-System implementieren",
    desc: "3 Groessen pro Erz-Typ: klein, mittel, gross. Groessere Erze = laengere Abbauzeit + mehr Drops. Basis fuer die gesamte Mining-Progression. WICHTIG: Muss in den ersten 10 Minuten spuerbar sein – Spieler sollen sofort den Unterschied zwischen klein/mittel/gross sehen und fuehlen. Visuell klar differenziert (Groesse + Partikel). Direkt auf Planet 1 erlebbar.",
    status: "backlog",
    priority: "critical",
    assignee: null,
    tags: ["mining", "feature"],
    created: "2026-03-16",
  },
  {
    id: "PM-004",
    title: "Level-/Progressions-System mit Zielen",
    desc: "Spieler muessen Ziele erreichen um aufzuleveln (z.B. 'Baue 100 Stein ab'). Hoeheres Level = laengerer Progress. Levelup schaltet naechsten Planeten frei. FOKUS: Erste 3 Level muessen in den ersten 10-20 Minuten erreichbar sein. Klare UI-Anzeige des Fortschritts. Jedes Levelup muss sich wie ein Belohnungsmoment anfuehlen (VFX + Sound). Retention-kritisch: Spieler braucht sofort ein sichtbares Ziel.",
    status: "backlog",
    priority: "critical",
    assignee: null,
    tags: ["system", "feature"],
    created: "2026-03-16",
  },
  {
    id: "PM-021",
    title: "Equipment UI / Pickaxe Icons ueberarbeiten",
    desc: "4 Premium Pickaxe-Icons importiert (2D Art als ImageLabels). Equipment GUI komplett redesigned: Overlay, Equipped-Banner mit Icon+Name+Buff, Icon-basierter Equipment-Button (52x52 mit [G] Badge), ZIndex-Hierarchie gefixt.",
    status: "done",
    priority: "high",
    assignee: "hannes",
    tags: ["ui", "pickaxe", "polish"],
    created: "2026-03-16",
    completed: "2026-03-18",
  },
  {
    id: "PM-022",
    title: "Divine Lightning Pickaxe (ersetzt Frostbite)",
    desc: "Frostbite wird durch 'Divine Lightning' ersetzt. Gelbes/goldenes Design statt blau. Gleicher Buff: +50% Mining Speed. Neues AI-generiertes 3D-Modell noetig. Blitz-Partikeleffekte in gelb/weiss.",
    status: "backlog",
    priority: "high",
    assignee: "hannes",
    tags: ["pickaxe", "feature"],
    created: "2026-03-16",
  },
  {
    id: "PM-023",
    title: "Neues 3D-Modell fuer Default Pickaxe",
    desc: "Die Standard-Pickaxe braucht ein neues AI-generiertes 3D-Modell. Soll simpel aber clean aussehen als Basis-Tool.",
    status: "backlog",
    priority: "high",
    assignee: "hannes",
    tags: ["pickaxe", "feature"],
    created: "2026-03-16",
  },
  {
    id: "PM-024",
    title: "Smarte Quest-Navigation",
    desc: "Die Navigation oben soll mit den aktuellen Quests matchen, nicht nur zum naechsten Erz fuehren. Beispiel: Quest 'need 25 Crystal + 500 Coins' → Navigation zum naechsten Crystal Ore. Wenn Material auf anderem Planet noetig, Navigation zu 'Planet XY'. Im Hub soll man auch zum richtigen Planeten gefuehrt werden.",
    status: "backlog",
    priority: "medium",
    assignee: null,
    tags: ["ui", "system", "feature"],
    created: "2026-03-16",
  },
  {
    id: "PM-025",
    title: "Automine Modus: Regenbogen-Effekte + Icon Button",
    desc: "Automine-Modus soll mit Regenbogen-Effekten visuell hervorgehoben werden. Statt Text-Button einen Icon-Button verwenden fuer cleanes UI.",
    status: "backlog",
    priority: "medium",
    assignee: null,
    tags: ["ui", "mining", "polish"],
    created: "2026-03-16",
  },
  {
    id: "PM-026",
    title: "Material-Liste nach Sonnensystem filtern",
    desc: "Die Materialliste links soll immer nur die Materialien vom aktuellen Sonnensystem anzeigen. Auf Sonnensystem 2 kein Stone mehr, sondern die Sonnensystem-2-Mats. Im Hub stattdessen Inventar-Button oder Gesamtanzeige nur beim Shop-Oeffnen.",
    status: "backlog",
    priority: "medium",
    assignee: null,
    tags: ["ui", "feature"],
    created: "2026-03-16",
  },
  {
    id: "PM-027",
    title: "Swing-Animationen ueberarbeiten (spaeter)",
    desc: "Deep Animation Polish ist aktuell deprioritisiert. Nur lightweight Anpassungen wenn sie direkt das Mining-Gefuehl verbessern (z.B. besseres Hit-Timing). Kein Blender-Rigging, keine Custom-Animationen. Aktuelle 3-Step Combo reicht als Basis.",
    status: "backlog",
    priority: "low",
    assignee: "hannes",
    tags: ["pickaxe", "polish"],
    created: "2026-03-16",
  },
  {
    id: "PM-028",
    title: "Sound FX Design (KI-generiert)",
    desc: "Komplettes Sound-Design mit KI (z.B. ElevenLabs). Benoetigt: Swoosh-Sounds beim Schwingen, Hitsounds auf Erzen (verschiedene Toene je nach Material), Ambient-Sounds, Levelup-Sounds, Shop-Sounds. Premium-Feeling durch hochwertige Sounds.",
    status: "backlog",
    priority: "high",
    assignee: "hannes",
    tags: ["audio", "polish"],
    created: "2026-03-16",
  },
  {
    id: "PM-029",
    title: "Dash-Mechanik mit Woosh-Sound",
    desc: "Dash-Bewegung per Doppel-Shift oder Button. Mit Woosh-Sound-Effekt. Schnelles, satisfying Movement auf Planeten. Nicht MVP-kritisch, kann nach Core-Loop kommen.",
    status: "backlog",
    priority: "low",
    assignee: null,
    tags: ["system", "audio", "feature"],
    created: "2026-03-16",
  },

  // --- BACKLOG: Mittelfristig ---
  {
    id: "PM-009",
    title: "Alle 7 Planeten fuer Sonnensystem 1 gestalten",
    desc: "7 Planeten mit progressiver Groessensteigerung. Jeder Planet hat eigenen Erz-Typ und eigenes visuelles Theme. Assets aus PurePoly Mining Pack verwenden. PRIORITAET: Planet 1 zuerst perfektionieren (siehe PM-050), dann schrittweise Planet 2-7. Nicht alle gleichzeitig.",
    status: "backlog",
    priority: "medium",
    assignee: null,
    tags: ["world", "feature"],
    created: "2026-03-16",
  },
  {
    id: "PM-012",
    title: "Hub als Raumschiff gestalten",
    desc: "Den Hub visuell als Raumschiff gestalten. Dort befinden sich Shops, Leaderboards. Socializing-Spot zwischen Sonnensystemen.",
    status: "backlog",
    priority: "medium",
    assignee: null,
    tags: ["world", "feature"],
    created: "2026-03-16",
  },
  {
    id: "PM-013",
    title: "Sonnensystem-Template-System",
    desc: "Template zum schnellen Hinzufuegen neuer Sonnensysteme mit groesseren Planeten und schwereren Erzen. Endlos skalierbar.",
    status: "backlog",
    priority: "medium",
    assignee: null,
    tags: ["system", "feature"],
    created: "2026-03-16",
  },
  {
    id: "PM-014",
    title: "Multiplayer: Spielerlimit pro Planet",
    desc: "Begrenzung der Spieler pro Planet (z.B. Planet 1: 5, Planet 2: 6, etc.) damit Maps nicht ueberlastet werden.",
    status: "backlog",
    priority: "medium",
    assignee: null,
    tags: ["multiplayer", "system"],
    created: "2026-03-16",
  },
  {
    id: "PM-015",
    title: "Taegliche Aufgaben System",
    desc: "Daily Quests die zum Wiederkommen animieren. Z.B. 'Baue heute 500 Erze ab' fuer Bonus-Belohnungen.",
    status: "backlog",
    priority: "medium",
    assignee: null,
    tags: ["system", "feature"],
    created: "2026-03-16",
  },

  // --- BACKLOG: Langfristig ---
  {
    id: "PM-016",
    title: "Cashshop (Robux) – Spezial-Pickaxes",
    desc: "Premium-Shop mit Robux-Waehrung. Spezielle Pickaxes (kosmetisch oder mit Bonus-Stats). Pay2Progress, nicht Pay2Win.",
    status: "backlog",
    priority: "low",
    assignee: null,
    tags: ["shop", "feature"],
    created: "2026-03-16",
  },
  {
    id: "PM-017",
    title: "Pet-System",
    desc: "Pets die dem Spieler folgen. Koennen im Cashshop oder durch Achievements freigeschaltet werden.",
    status: "backlog",
    priority: "low",
    assignee: null,
    tags: ["system", "feature"],
    created: "2026-03-16",
  },
  {
    id: "PM-018",
    title: "Lokalisierung (weitere Sprachen)",
    desc: "Spiel auf Englisch ist Basis. Weitere Sprachen hinzufuegen um globale Roblox-Community anzusprechen.",
    status: "backlog",
    priority: "low",
    assignee: null,
    tags: ["system", "feature"],
    created: "2026-03-16",
  },
  {
    id: "PM-019",
    title: "Sonnensystem 2 + 3 erstellen",
    desc: "Neue Sonnensysteme mit noch groesseren Planeten und haerteren Erzen. Verwendung des Template-Systems.",
    status: "backlog",
    priority: "low",
    assignee: null,
    tags: ["world", "feature"],
    created: "2026-03-16",
  },
  {
    id: "PM-020",
    title: "Absurde Planeten-Skalierung im Endgame",
    desc: "Der uebertriebene Aspekt: Endgame-Planeten werden absurd riesig. Das ist der 'wow'-Faktor wie bei den riesigen Fischen im Fishing Game.",
    status: "backlog",
    priority: "low",
    assignee: null,
    tags: ["world", "polish"],
    created: "2026-03-16",
  },
  {
    id: "PM-030",
    title: "Discord Community Bot (n8n)",
    desc: "Discord-Server mit n8n-Bot im Background: Chat-Analyse, Traffic reinbringen, Stats tracken, Community-Management automatisieren.",
    status: "backlog",
    priority: "low",
    assignee: null,
    tags: ["system", "feature"],
    created: "2026-03-16",
  },
  {
    id: "PM-031",
    title: "Game Wiki erstellen",
    desc: "Wiki mit allen wichtigen Spieldaten, Tutorials, Guides, Erz-Tabellen, Upgrade-Kosten. Als Referenz fuer Spieler und Entwickler.",
    status: "backlog",
    priority: "low",
    assignee: null,
    tags: ["feature"],
    created: "2026-03-16",
  },
  {
    id: "PM-032",
    title: "YouTube + TikTok Content fuer Traffic",
    desc: "YouTube- und TikTok-Accounts erstellen. Clips aus dem Game posten um Traffic und Spielerbasis zu generieren. Gameplay-Highlights, Updates, Tutorials.",
    status: "backlog",
    priority: "low",
    assignee: null,
    tags: ["feature"],
    created: "2026-03-16",
  },

  // --- NPC SYSTEM ---
  {
    id: "PM-040",
    title: "NPC-System funktional fertigstellen (ohne Rigging/Animation)",
    desc: "Alle 4 NPCs (Wizzle, Chubbs, Drillo, Tinker) als funktionale Gameplay-Ankerpunkte im Hub. FOKUS: Interact-Prompts, Click-Flow, korrekte UI oeffnen, klare Rollen-Lesbarkeit. Placeholder/statische Modelle sind OK – kein Rigging oder Custom-Animation noetig. Wichtig: Jeder NPC muss seine Funktion klar kommunizieren (Farbe, Nametag, Proximity-Prompt-Text).",
    status: "backlog",
    priority: "critical",
    assignee: null,
    tags: ["system", "feature"],
    created: "2026-03-20",
  },
  {
    id: "PM-041",
    title: "Wizzle the Wizard \u2013 Stage-Wechsel-NPC",
    desc: "Wizzle als Dimensions-/Stage-NPC implementieren. Portal-UI mit Stage-Auswahl, Anzeige freigeschalteter Stages, Portal-Teleport-Effekt. Ersetzt das bisherige Portal-System.",
    status: "backlog",
    priority: "high",
    assignee: null,
    tags: ["system", "feature", "world"],
    created: "2026-03-20",
  },
  {
    id: "PM-042",
    title: "Chubbs the Trader \u2013 Sell-NPC",
    desc: "Chubbs als Sell-NPC implementieren. Sell-UI mit Material-Inventar und Preisanzeige. Ersetzt das bisherige Sell-Board komplett. Proximity-Prompt + Click-to-sell.",
    status: "backlog",
    priority: "high",
    assignee: null,
    tags: ["shop", "feature"],
    created: "2026-03-20",
  },
  {
    id: "PM-043",
    title: "Drillo the Miner \u2013 Premium-Pickaxe-NPC",
    desc: "Drillo als Premium-Pickaxe-Shop-NPC implementieren. Robux-Shop mit Pickaxe-Stats, Buff-Vorschau und Partikel-Preview. Pay2Progress Ansatz beibehalten.",
    status: "backlog",
    priority: "high",
    assignee: null,
    tags: ["shop", "pickaxe", "feature"],
    created: "2026-03-20",
  },
  {
    id: "PM-044",
    title: "Tinker the Upgrader \u2013 Upgrade-NPC",
    desc: "Tinker als Upgrade-NPC implementieren. Upgrade-UI mit allen Kategorien (Damage, Speed, Boots, Jump, Coins, Luck). Aktuelle Stufe + naechster Preis sichtbar.",
    status: "backlog",
    priority: "high",
    assignee: null,
    tags: ["shop", "system", "feature"],
    created: "2026-03-20",
  },
  {
    id: "PM-045",
    title: "NPC-Dialog-/Prompt-System vorbereiten",
    desc: "Wiederverwendbares Dialog-System fuer alle NPCs: Proximity-Prompt bei Annaeherung, kurze Begruessung, dann UI-Oeffnung. Spaeter erweiterbar fuer Quests und Lore.",
    status: "backlog",
    priority: "medium",
    assignee: null,
    tags: ["system", "ui", "feature"],
    created: "2026-03-20",
  },
  {
    id: "PM-046",
    title: "NPC-Modelle & Platzierung im Hub (Placeholder OK)",
    desc: "Modelle/Meshes fuer alle 4 NPCs. Passende Standorte im Hub festlegen. Nametags und visuelle Erkennbarkeit (Farben). AKTUELL: Statische Placeholder-Modelle reichen voellig – kein Rigging oder Custom-Animation noetig. Fokus auf klare visuelle Unterscheidbarkeit der Rollen.",
    status: "backlog",
    priority: "medium",
    assignee: null,
    tags: ["world", "polish"],
    created: "2026-03-20",
  },
  {
    id: "PM-047",
    title: "NPC-UI-Interaktionen planen & umsetzen",
    desc: "Einheitliches UI-Pattern fuer NPC-Interaktionen: Sell-UI (Chubbs), Upgrade-UI (Tinker), Shop-UI (Drillo), Portal-UI (Wizzle). Konsistenter Look, smooth open/close Animationen.",
    status: "backlog",
    priority: "medium",
    assignee: null,
    tags: ["ui", "feature"],
    created: "2026-03-20",
  },
  {
    id: "PM-048",
    title: "NPC-Lore, Identity & Animation Polish (spaeter)",
    desc: "Flavor-Texte, Idle-Animationen, Partikel-Effekte. DEPRIORITISIERT: Animation-Polish ist aktuell kein Fokus. Kommt erst wenn Core-Gameplay und NPC-Funktionalitaet stehen.",
    status: "backlog",
    priority: "low",
    assignee: null,
    tags: ["polish", "feature"],
    created: "2026-03-20",
  },

  // --- NEUE TICKETS: Gameplay-Polish & Retention ---
  {
    id: "PM-049",
    title: "Mining-Feedback / Hit-Feel polishen",
    desc: "Das Mining soll sich maximal satisfying anfuehlen. Konkret: Hit-Impact verstaerken (kurzer Freeze-Frame oder leichter Screen-Shake), Ore-Reaktion bei jedem Treffer (Wackeln/Flash), Floating Numbers konsistenter und groesser, klare visuelle Unterscheidung der 3 Erz-Groessen beim Abbau, Material-Drop-Animation. Ziel: Erste Session soll suchtig machen.",
    status: "backlog",
    priority: "critical",
    assignee: null,
    tags: ["mining", "polish", "feature"],
    created: "2026-03-23",
  },
  {
    id: "PM-050",
    title: "Planet 1 als Vertical Slice perfektionieren",
    desc: "Planet 1 wird zur perfekten Demo des Spiels. Erz-Verteilung optimieren (genug Nodes, guter Abstand), Dekoration verdichten (Baeume, Gras, Kristalle, Felsen), Lesbarkeit der Erze (Farbe/Groesse sofort erkennbar), Traversal-Gefuehl testen (Sprint, Planeten-Lauf), First-Session Onboarding-Qualitaet pruefen. Planet 1 muss alleine schon Spass machen.",
    status: "backlog",
    priority: "high",
    assignee: null,
    tags: ["world", "mining", "polish"],
    created: "2026-03-23",
  },
  {
    id: "PM-051",
    title: "Offline Rewards Basis-System",
    desc: "Spieler erhalten beim Einloggen Belohnungen basierend auf Offline-Zeit. Implementierung: Last-Logout Timestamp speichern, Offline-Earnings berechnen (z.B. passive Mineralien), Join-Reward-Popup mit Zusammenfassung. Balance: Genug fuer Motivation, nicht Economy-brechend. Cap bei z.B. 8 Stunden. Retention-kritisch.",
    status: "backlog",
    priority: "high",
    assignee: null,
    tags: ["system", "feature"],
    created: "2026-03-23",
  },
  {
    id: "PM-052",
    title: "First 10 Minutes / New Player Flow polishen",
    desc: "Die ersten 10 Minuten entscheiden ob Spieler bleiben. Konkret: Klare Ziel-Anzeige von Anfang an (was soll ich tun?), erster Sell-Moment fuehlt sich belohnend an, erstes Upgrade ist spuerbar staerker, sichtbare Kurzzeit-Ziele (Progress-Bar zum naechsten Level), Motivation zum naechsten Planeten aufbauen. Kein formales Tutorial – Learning by Doing mit UI-Hints.",
    status: "backlog",
    priority: "high",
    assignee: null,
    tags: ["ui", "system", "polish"],
    created: "2026-03-23",
  },
  {
    id: "PM-053",
    title: "Pickaxe-Gefuehl und Premium-Fantasy staerker herausarbeiten",
    desc: "Jede Pickaxe soll sich einzigartig anfuehlen, nicht nur anders aussehen. Inferno: feuriger Impact, Hitmarker in Orange, Feuer-Sounds. Lightning: schnellere Swing-Animationsgeschwindigkeit spuerbar, Elektro-Sounds, blaue Hitmarker. Void: groesserer Hitbereich visuell sichtbar (Lila Aura), ghostige Sounds. Ziel: Premium-Pickaxes muessen sich DESIRABLE anfuehlen – Spieler sollen sie WOLLEN.",
    status: "backlog",
    priority: "high",
    assignee: null,
    tags: ["pickaxe", "audio", "polish"],
    created: "2026-03-23",
  },

  // --- BACKLOG: UI Polish ---
  {
    id: "PM-033",
    title: "Sell & Upgrade Shop auf Premium-Level bringen",
    desc: "Sell Shop (HubClient) und Upgrade Shop (UpgradeShopClient) auf das gleiche Premium-Design-Level wie den Pickaxe Shop bringen. Element-Gradients, Glow-Borders, integrierte Preis-Buttons, 3D-Schatten auf Buttons.",
    status: "backlog",
    priority: "medium",
    assignee: "hannes",
    tags: ["ui", "shop", "polish"],
    created: "2026-03-18",
  },

  // --- DONE ---
  {
    id: "PM-034",
    title: "Unified Shop UI Theme",
    desc: "Alle 3 Shop-UIs (Upgrades, Sell, Pickaxe) vereinheitlicht: Konsistente Panel-Groessen (440x520), 52px Header mit BG, 32x32 Close-Buttons, einheitliche Row-Styles, ZIndex-Hierarchie (Overlay=10, Panel=11+), Accent-Farben pro Shop (Purple/Green/Gold).",
    status: "done",
    priority: "high",
    assignee: "hannes",
    tags: ["ui", "shop", "polish"],
    created: "2026-03-18",
    completed: "2026-03-18",
  },
  {
    id: "PM-035",
    title: "Premium Pickaxe Cash Shop (Brawl Stars Style)",
    desc: "Pickaxe Shop komplett redesigned: Element-getoennte Card-Gradients, Glow-Borders und Icon-Container pro Element, Top-Accent-Bars, Pill-Badges fuer Buffs und Kosten, integrierte Preis-Buttons (Coin+Preis+BUY) mit 3D-Shadow-Effekt, Hover-Animationen.",
    status: "done",
    priority: "high",
    assignee: "hannes",
    tags: ["ui", "shop", "polish"],
    created: "2026-03-18",
    completed: "2026-03-18",
  },
  {
    id: "PM-001",
    title: "Pickaxe-Animationen fixen + 3-Step Combo",
    desc: "Swing-Animationen komplett ueberarbeitet: 3-Hit Combo (Links → Rechts → Links). Jeder Schlag mit Windup (hoch) → Slam (runter) → Return. Smooth Sine-Easing, Ore-Flash-Feedback.",
    status: "done",
    priority: "critical",
    assignee: "hannes",
    tags: ["pickaxe", "bug"],
    created: "2026-03-16",
    completed: "2026-03-16",
  },
  {
    id: "PM-002",
    title: "Importierte 3D-Modelle korrekt einbauen",
    desc: "Die aus dem Unity Asset Store importierten Pickaxe-Modelle sind jetzt korrekt eingebaut. Skalierung (0.07x), Motor6D-Weld an RightHand, CFrame-Rotation fixiert. Base-Pickaxe-Konflikt mit MiningClient geloest.",
    status: "done",
    priority: "critical",
    assignee: "hannes",
    tags: ["pickaxe", "bug"],
    created: "2026-03-16",
    completed: "2026-03-16",
  },
  {
    id: "PM-005",
    title: "Schadenszahlen-Anzeige an Erzen",
    desc: "Schadenszahlen poppen beim Abbauen ueber dem Erz auf. Zahlen erhoehen sich mit Upgrades.",
    status: "done",
    priority: "high",
    assignee: "hannes",
    tags: ["mining", "ui", "polish"],
    created: "2026-03-16",
    completed: "2026-03-16",
  },
  {
    id: "PM-006",
    title: "Sound FX Grundgeruest (Hitsounds + Schwung)",
    desc: "Basis-Sound-Feedback beim Mining eingebaut. Weitere Sounds (KI-generiert) als separates Ticket PM-028.",
    status: "done",
    priority: "high",
    assignee: "hannes",
    tags: ["audio", "polish"],
    created: "2026-03-16",
    completed: "2026-03-16",
  },
  {
    id: "PM-007",
    title: "Sprint-Mechanik",
    desc: "Spieler koennen sprinten fuer cleanes, schnelles Movement auf den Planeten.",
    status: "done",
    priority: "medium",
    assignee: "hannes",
    tags: ["system", "feature"],
    created: "2026-03-16",
    completed: "2026-03-16",
  },
  {
    id: "PM-008",
    title: "Balance-Config Modul",
    desc: "Zentrale Config (300 Zeilen) mit allen Balance-Werten: 3 Sonnensysteme, 21 Planeten, 21 Erz-Typen, 6 Upgrades, Level-Kosten, Helper-Funktionen. Alles zentral anpassbar.",
    status: "done",
    priority: "high",
    assignee: "hannes",
    tags: ["system", "feature"],
    created: "2026-03-16",
    completed: "2026-03-16",
  },
  {
    id: "PM-010",
    title: "Shop-UI: Materialien verkaufen + Upgrades kaufen",
    desc: "Shop-System komplett: Sell-Board fuer Materialien, Upgrade-Shop mit 6 Kategorien (Damage, Speed, Boots, Jump, Coins, Luck), Pickaxe-Shop. Proximity + Click-to-open. Auto-close Bug gefixt.",
    status: "done",
    priority: "medium",
    assignee: "hannes",
    tags: ["shop", "ui", "feature"],
    created: "2026-03-16",
    completed: "2026-03-16",
  },
  {
    id: "PM-011",
    title: "Leaderboard-UI (mehrere Kategorien)",
    desc: "3 Leaderboards im Hub: Power Level (orange), Top Levels (lila), Top Balance (gold). Server-seitig sortiert, Live-Updates alle 10 Sekunden.",
    status: "done",
    priority: "medium",
    assignee: "hannes",
    tags: ["ui", "feature"],
    created: "2026-03-16",
    completed: "2026-03-16",
  },
  {
    id: "PM-109",
    title: "Fredoka Font eingebaut",
    desc: "Alle UI-Texte im Spiel von Gotham auf FredokaOne umgestellt (73 Instanzen in 8 Scripts). Trendy Roblox-Look.",
    status: "done",
    priority: "medium",
    assignee: "hannes",
    tags: ["ui", "polish"],
    created: "2026-03-16",
    completed: "2026-03-16",
  },
  {
    id: "PM-110",
    title: "Inferno Pickaxe mit Feuer-Effekten",
    desc: "AI-generiertes 3D-Modell importiert. FireTrail (Rate 200), FireSparks (Rate 40), FireGlow PointLight. Per-Pickaxe Grip-Offset-System mit Attributen.",
    status: "done",
    priority: "high",
    assignee: "hannes",
    tags: ["pickaxe", "feature", "polish"],
    created: "2026-03-16",
    completed: "2026-03-16",
  },
  {
    id: "PM-111",
    title: "Void Pickaxe mit Ghost-Effekten",
    desc: "AI-generiertes 3D-Modell (schwarz/lila). VoidTrail, VoidWisps, VoidSouls Partikel + VoidGlow PointLight. Buff: +50% Attack Range. Ersetzt Midas Touch.",
    status: "done",
    priority: "high",
    assignee: "hannes",
    tags: ["pickaxe", "feature", "polish"],
    created: "2026-03-16",
    completed: "2026-03-16",
  },
  {
    id: "PM-112",
    title: "Dev Dashboard mit Firebase",
    desc: "GitHub Pages Dashboard (Planet Miner Dev HQ) mit Firebase Firestore fuer Echtzeit-Sync. Ticket-System, Vision, Roadmap, Systeme, Wirtschaft, Spielerreise. Mehrspieler-Login (Hannes + Lamar).",
    status: "done",
    priority: "medium",
    assignee: "hannes",
    tags: ["system", "feature"],
    created: "2026-03-16",
    completed: "2026-03-16",
  },
  {
    id: "PM-100",
    title: "Planeten-Lauf-Mechanik (Mario Galaxy)",
    desc: "Spieler koennen um sphaerische Planeten herumlaufen. Das Kern-USP des Spiels.",
    status: "done",
    priority: "critical",
    assignee: "hannes",
    tags: ["system", "feature"],
    created: "2025-01-01",
    completed: "2025",
  },
  {
    id: "PM-101",
    title: "Mining-System Grundgeruest",
    desc: "Client- und Server-seitiges Mining mit RemoteEvents (MineNode, MaterialGiven, NodeRespawned).",
    status: "done",
    priority: "critical",
    assignee: "hannes",
    tags: ["mining", "feature"],
    created: "2025-01-01",
    completed: "2025",
  },
  {
    id: "PM-102",
    title: "3 Sonnensystem-Folder + Hub-Model",
    desc: "Workspace-Struktur mit Sonnensystem1/2/3 Foldern und Hub Model.",
    status: "done",
    priority: "high",
    assignee: "hannes",
    tags: ["world"],
    created: "2025-01-01",
    completed: "2025",
  },
  {
    id: "PM-103",
    title: "Shop & Leaderboard Grundgeruest",
    desc: "Server- und Client-Scripts fuer Shop-System und Leaderboards.",
    status: "done",
    priority: "high",
    assignee: "hannes",
    tags: ["shop", "ui"],
    created: "2025-01-01",
    completed: "2025",
  },
  {
    id: "PM-104",
    title: "Pickaxe-System + 3 Test-Pickaxes",
    desc: "PickaxeServer, PickaxeClient, PickaxeBuffs Modul. 3 Test-Pickaxes eingebaut.",
    status: "done",
    priority: "high",
    assignee: "hannes",
    tags: ["pickaxe", "feature"],
    created: "2025-01-01",
    completed: "2025",
  },
  {
    id: "PM-105",
    title: "DataService + Dimension Portals",
    desc: "Datenpersistenz und Portal-System zwischen Dimensionen/Sonnensystemen.",
    status: "done",
    priority: "high",
    assignee: "hannes",
    tags: ["system"],
    created: "2025-01-01",
    completed: "2025",
  },
  {
    id: "PM-106",
    title: "3D-Modelle + Texturen importiert",
    desc: "Mining Asset Packs aus Unity Store importiert: Erz-Modelle, Pickaxe-Modelle, Texturen.",
    status: "done",
    priority: "medium",
    assignee: "hannes",
    tags: ["world"],
    created: "2025-01-01",
    completed: "2025",
  },
  {
    id: "PM-107",
    title: "Controller-Module (Camera, Anim, Planet)",
    desc: "CameraController, AnimController, PlanetController als separate Module.",
    status: "done",
    priority: "high",
    assignee: "hannes",
    tags: ["system"],
    created: "2025-01-01",
    completed: "2025",
  },
  {
    id: "PM-108",
    title: "Health Manager + OreTemplates",
    desc: "HealthManager Script und OreTemplates Folder eingerichtet.",
    status: "done",
    priority: "medium",
    assignee: "hannes",
    tags: ["mining", "system"],
    created: "2025-01-01",
    completed: "2025",
  },
  {
    id: "PM-054",
    title: "Overhead Display Redesign (Name + PL Badge)",
    desc: "OverheadServer komplett ueberarbeitet: Altes grosses PL-Feld ersetzt durch kompaktes Layout mit Name + Pill-Badge (PowerLevel) in oberer Zeile und Level darunter. Badge hat Tier-Farben (Rookie-Legendary), UICorner, UIStroke mit Gradient, Glow fuer hohe Tiers. BillboardGui nutzt Scale-basierte Sizes (nicht Pixel). Auf Hub und Stage1 synchronisiert.",
    status: "done",
    priority: "high",
    assignee: "hannes",
    tags: ["ui", "polish"],
    created: "2026-03-24",
    completed: "2026-03-24",
  },
  {
    id: "PM-055",
    title: "PL Badge im Info Panel (Pill-shaped)",
    desc: "Orange 'PL: 20' TextLabel im Info Panel (oben links) ersetzt durch Pill-shaped Badge mit Tier-Farben. Gleiche Tier-Definitionen wie Overhead (7 Stufen: Rookie-Legendary). updatePlBadge() Funktion aktualisiert Badge-Farbe, Border und Gradient je nach PowerLevel. Auf Hub und Stage1 synchronisiert.",
    status: "done",
    priority: "high",
    assignee: "hannes",
    tags: ["ui", "polish"],
    created: "2026-03-24",
    completed: "2026-03-24",
  },
  {
    id: "PM-056",
    title: "Level-Up Button Fix (Hub)",
    desc: "Level-Up Button im Hub zeigt falsche Farbe/Status an. Button ist gruen obwohl Anforderungen nicht erfuellt (sollte rot sein mit 'Need: X Material + Y Coins'). Probleme: updateLevelUpButton Timing, shopDataEvent ruft Update vor Materials-Update auf. Teilweise gefixt (Reihenfolge + Fallback bei nil cost), aber Button-Anzeige muss noch verifiziert werden.",
    status: "progress",
    priority: "high",
    assignee: "hannes",
    tags: ["ui", "bug"],
    created: "2026-03-24",
  },

  // --- NEUE TICKETS: Automation & Profile ---
  {
    id: "PM-057",
    title: "Auto-Walk zum naechsten Erz",
    desc: "Automatisches Laufen zum naechst gelegenen Erz auf dem aktuellen Planeten. Bei Quest-Anforderung soll Auto-Walk auch Planetenwechsel vorschlagen/ausfuehren (z.B. 'Need Crystal' → laufe zu Crystal-Planet). Basis-Feature fuer spaetere Premium-Automation.",
    status: "backlog",
    priority: "medium",
    assignee: null,
    tags: ["system", "feature"],
    created: "2026-03-25",
  },
  {
    id: "PM-058",
    title: "Auto-Mine als Premium/Battlepass Feature",
    desc: "Auto-Walk + Auto-Mine als Battlepass/Premium-Abo Feature. Spieler kauft Abo und kann AFK farmen. Button-UI zum Aktivieren/Deaktivieren. Regenbogen-Effekte wenn aktiv. Pay2Progress, nicht Pay2Win. Erstmal als Test-Buttons ohne Paywall implementieren.",
    status: "backlog",
    priority: "medium",
    assignee: null,
    tags: ["system", "shop", "feature"],
    created: "2026-03-25",
  },
  {
    id: "PM-059",
    title: "Player Profile (Avatar + Stats)",
    desc: "Spielerprofil-Button der das Roblox-Avatar-Bild des Spielers zeigt. Beim Klick oeffnet sich ein Profil-Overlay mit: Avatar, Username, Level, PowerLevel, abgebaute Erze nach Typ (Lifetime Stats), Lieblings-Pickaxe, Spielzeit. Daten aus DataService lesen.",
    status: "backlog",
    priority: "medium",
    assignee: null,
    tags: ["ui", "system", "feature"],
    created: "2026-03-25",
  },
  {
    id: "PM-060",
    title: "Sound FX komplett implementieren",
    desc: "Alle fehlenden Sound-Effekte einbauen: Swing-Swoosh pro Combo-Step, Hit-Sounds je nach Erz-Material, Combo-5 Power-Hit Sound, Level-Up Fanfare, Shop open/close, Buy/Sell Sounds, Ambient Planet-Sounds, Portal-Teleport Sound. KI-generierte Sounds (ElevenLabs/Suno). Siehe auch PM-028.",
    status: "backlog",
    priority: "high",
    assignee: "hannes",
    tags: ["audio", "polish"],
    created: "2026-03-25",
  },
  {
    id: "PM-061",
    title: "Hit-Effekte & Splinter-Partikel auf Erzen",
    desc: "Beim Erz-Hit: Leichter Impact-Partikel + Steinsplitter die vom Erz wegfliegen. 80% graue Splitter, 20% in Planetenfarbe. Combo-5 Power-Hit hat breitere Streuung und mehr Partikel. Splitter haben Gravitation und Drag fuer realistisches Gefuehl.",
    status: "done",
    priority: "high",
    assignee: "hannes",
    tags: ["mining", "polish"],
    created: "2026-03-25",
    completed: "2026-03-25",
  },
  {
    id: "PM-062",
    title: "Combo-5 Power-Hit mit 25% Bonus-Damage",
    desc: "5. Schlag in der Combo-Kette macht 25% mehr Schaden. ComboStep wird vom Client zum Server geschickt. Damage-Popup fuer Power-Hits in Gelb mit schwarzer Kontur (statt weiss). Leicht groesser mit Punch-In Animation.",
    status: "done",
    priority: "high",
    assignee: "hannes",
    tags: ["mining", "feature"],
    created: "2026-03-25",
    completed: "2026-03-25",
  },
  {
    id: "PM-063",
    title: "Planetenfarben an Erz-Gems angepasst",
    desc: "Alle 21 Planeten in Config farblich an ihre jeweiligen Erz-Gem-Texturen angepasst. Stone=Gruen, Copper=Orange, Iron=Silberblau, Gold=Gelb, Crystal=Blau, Star Ore=Rot etc. Splitter-Partikel nutzen diese Farben.",
    status: "done",
    priority: "medium",
    assignee: "hannes",
    tags: ["world", "polish"],
    created: "2026-03-25",
    completed: "2026-03-25",
  },
  {
    id: "PM-064",
    title: "Hub Portal Void-Theme Redesign",
    desc: "Dimensions-Portal im Hub komplett ueberarbeitet: Drain-Asset + Black-Hole-Asset importiert, alle Partikel auf Void-Pink Theme (220,50,255 bis 100,10,160) umgefaerbt. Drain rotiert langsam um Y-Achse. Atmosphaerisches Void-Portal.",
    status: "done",
    priority: "medium",
    assignee: "hannes",
    tags: ["world", "polish"],
    created: "2026-03-25",
    completed: "2026-03-25",
  },
];

// ============================================================
// VISION
// ============================================================
const VISION = {
  pitch: {
    title: "Planet Miner \u2013 Space Mining Tycoon",
    description: "Laufe um kugelfoermige Planeten wie in Mario Galaxy. Baue Erze ab, upgrade deine Pickaxe, schalte neue Welten frei. Grinde dich durch Sonnensysteme \u2013 allein oder mit Freunden.",
    quote: "\"Walk on planets. Mine everything. Become legendary.\"",
  },
  coreFeeling: {
    title: "Das Kern-Erlebnis",
    subtitle: "Was soll ein Spieler fuehlen?",
    items: [
      { icon: "\uD83E\uDD29", label: "Satisfying",  desc: "Jeder Hit fuehlt sich gut an" },
      { icon: "\uD83C\uDFAF", label: "Ziele",       desc: "Immer das naechste Level im Blick" },
      { icon: "\uD83D\uDCAA", label: "Power",       desc: "Spuerbar staerker werden" },
      { icon: "\uD83C\uDF0D", label: "Erkundung",   desc: "Neue Planeten entdecken" },
    ],
  },
  usp: {
    title: "Alleinstellungsmerkmale",
    points: [
      { icon: "\uD83C\uDF0F", title: "Planeten-Laufen", desc: "Spieler laufen um sphaerische Planeten \u2013 wie Mario Galaxy. Unser Markenzeichen fuer ALLE zukuenftigen Spiele." },
      { icon: "\uD83D\uDCC8", title: "Absurde Skalierung", desc: "Planeten werden progressiv riesig. Endgame-Planeten sind absurd gross \u2013 der uebertriebene Aspekt, den Roblox-Spieler lieben." },
      { icon: "\uD83C\uDFB5", title: "Juice & Dopamin", desc: "Schadenszahlen, Hitsounds, Schwung-Sounds, Screen-Shake \u2013 maximales Feedback bei jedem Schlag." },
    ],
  },
  multiplayer: {
    title: "Solo vs Multiplayer",
    solo:  { icon: "\uD83D\uDC64", label: "Solo-Spieler",  desc: "Alleine grinden, eigenes Tempo, voller Fokus." },
    multi: { icon: "\uD83D\uDC65", label: "Mit Freunden",  desc: "Zusammen auf Planeten abbauen, im Hub abhaengen, Leaderboards vergleichen." },
  },
};

// ============================================================
// SYSTEME
// ============================================================
const SYSTEME = [
  {
    icon: "\u26CF\uFE0F",
    iconClass: "mining",
    title: "Mining-System",
    desc: "Kern-Gameplay: Erze abbauen auf Planeten",
    details: [
      "3 Erz-Groessen pro Typ (klein, mittel, gross)",
      "Groesser = laengere Abbauzeit + mehr Drops",
      "Hoehere Planeten = haertere Erze",
      "Visuelles Feedback: Schadenszahlen, Partikel, Sounds",
      "RemoteEvents: MineNode, MaterialGiven, NodeRespawned",
    ],
  },
  {
    icon: "\uD83E\uDE93",
    iconClass: "pickaxe",
    title: "Pickaxe-System",
    desc: "Werkzeuge mit Upgrades und Buffs",
    details: [
      "Verschiedene Pickaxes mit unterschiedlichen Stats",
      "Upgrade-Pfade: Mehr Schaden, mehr Drops",
      "Spezial-Pickaxes im Cashshop (Robux)",
      "PickaxeBuffs Modul fuer Stat-Berechnung",
      "Animationen fuer Schwing- und Hit-Effekte",
    ],
  },
  {
    icon: "\uD83C\uDF0D",
    iconClass: "planet",
    title: "Planeten-System",
    desc: "Progression durch immer groessere Welten",
    details: [
      "7 Planeten pro Sonnensystem",
      "Progressive Groessensteigerung",
      "Jeder Planet hat eigenen Erz-Typ",
      "Spielerlimit pro Planet (5-10 Spieler)",
      "Freischaltung durch Level-System",
    ],
  },
  {
    icon: "\u2600\uFE0F",
    iconClass: "solar",
    title: "Sonnensystem-Progression",
    desc: "Uebergeordnete Progression mit Portalen",
    details: [
      "Mehrere Sonnensysteme (aktuell 3 angelegt)",
      "Template-System fuer schnelles Hinzufuegen",
      "Dimension Portals zum Reisen",
      "Jedes System schwerer als das vorherige",
      "Endlos erweiterbar bei Bedarf",
    ],
  },
  {
    icon: "\uD83D\uDE80",
    iconClass: "hub",
    title: "Hub / Raumschiff",
    desc: "Zentraler Hangout zwischen Sonnensystemen",
    details: [
      "Socializing & Hangout Spot",
      "Shop-System: Materialien verkaufen",
      "Upgrade-Shop: Pickaxe & Player Upgrades",
      "Mehrere Leaderboards",
      "Cashshop (Robux)",
    ],
  },
  {
    icon: "\uD83D\uDCBE",
    iconClass: "data",
    title: "Daten & Persistence",
    desc: "Speicherung von Spielerfortschritt",
    details: [
      "DataService Modul auf Server",
      "Spielerdaten: Level, Inventar, Waehrung",
      "Leaderboard-Daten",
      "Taegliche Aufgaben Tracking",
    ],
  },
];

// ============================================================
// WIRTSCHAFT
// ============================================================
const WIRTSCHAFT = {
  currency: {
    title: "Waehrungs-System",
    items: [
      { icon: "\uD83E\uDE99", name: "Mineralien",        desc: "Hauptwaehrung \u2013 durch Erz-Verkauf im Shop verdient" },
      { icon: "\uD83D\uDCB5", name: "Robux (Echtgeld)",  desc: "Premium-Waehrung fuer Cashshop-Items" },
    ],
  },
  shops: {
    title: "Shop-Systeme",
    items: [
      { icon: "\uD83C\uDFEA", name: "Material-Shop",    desc: "Abgebaute Erze verkaufen fuer Mineralien" },
      { icon: "\u2B06\uFE0F",  name: "Upgrade-Shop",     desc: "Pickaxe-Damage, Drop-Rate, Player-Buffs" },
      { icon: "\uD83D\uDC8E", name: "Cashshop (Robux)", desc: "Premium-Pickaxes, Pets, Kosmetik" },
    ],
  },
  balance: {
    title: "Balance-Prinzipien",
    points: [
      "Alle Werte zentral in Config \u2013 jederzeit anpassbar",
      "Exponentielle Kurven: Spaetere Level dauern deutlich laenger",
      "Free-to-Play muss alles erreichen koennen (Pay2Progress, nicht Pay2Win)",
      "Cashshop-Items duerfen Vorteil geben, aber nicht zwingend sein",
    ],
  },
};

// ============================================================
// ROADMAP
// ============================================================
const ROADMAP = [
  {
    phase: "Phase 1 \u2013 Foundation & Core Loop",
    icon: "\uD83C\uDFD7\uFE0F",
    status: "in-progress",
    items: [
      { id: "p1-mining-loop",     text: "Core Mining Loop (HP-basiert, Combos) \u2705" },
      { id: "p1-mining-feel",     text: "Mining-Feedback / Hit-Feel polishen (PM-049)" },
      { id: "p1-ore-sizes",       text: "Erz-Groessen implementieren (PM-003)" },
      { id: "p1-level-system",    text: "Level-/Progressions-System (PM-004)" },
      { id: "p1-planet1-slice",   text: "Planet 1 als Vertical Slice (PM-050)" },
      { id: "p1-new-player",      text: "First 10 Minutes / New Player Flow (PM-052)" },
      { id: "p1-npc-system",      text: "NPC-System funktional (PM-040)" },
      { id: "p1-npc-wizzle",      text: "Wizzle Stage-Wechsel (PM-041)" },
      { id: "p1-npc-chubbs",      text: "Chubbs Sell-NPC (PM-042)" },
      { id: "p1-npc-drillo",      text: "Drillo Premium-Shop (PM-043)" },
      { id: "p1-npc-tinker",      text: "Tinker Upgrades (PM-044)" },
      { id: "p1-pickaxe-feel",    text: "Pickaxe Premium-Fantasy (PM-053)" },
      { id: "p1-offline-rewards", text: "Offline Rewards Basis (PM-051)" },
      { id: "p1-sound-fx",        text: "Sound FX Design (PM-028)" },
      { id: "p1-balance-config",  text: "Balance-Config System \u2705" },
      { id: "p1-swing-anim",      text: "Pickaxe-Animationen \u2705" },
      { id: "p1-pickaxe-models",  text: "Pickaxe 3D-Modelle + Effekte \u2705" },
      { id: "p1-fredoka-ui",      text: "Fredoka Font & UI Polish \u2705" },
      { id: "p1-dev-dashboard",   text: "Dev Dashboard mit Firebase \u2705" },
      { id: "p1-sprint",          text: "Sprint-Mechanik \u2705" },
      { id: "p1-dmg-numbers",     text: "Schadenszahlen-Anzeige \u2705" },
      { id: "p1-equipment-ui",    text: "Equipment UI Redesign \u2705" },
      { id: "p1-overhead-display", text: "Overhead Display Redesign (Name + PL Badge) \u2705" },
      { id: "p1-pl-badge-info",    text: "PL Badge im Info Panel \u2705" },
      { id: "p1-stage-hub-sync",   text: "Stage1 <-> Hub Full Sync \u2705" },
      { id: "p1-levelup-btn-fix",  text: "Level-Up Button Fix Hub (PM-056)" },
      { id: "p1-hit-splinter",     text: "Hit-Effekte & Splinter-Partikel \u2705" },
      { id: "p1-combo5-bonus",     text: "Combo-5 Power-Hit +25% Damage \u2705" },
      { id: "p1-planet-colors",    text: "Planetenfarben an Erz-Gems \u2705" },
      { id: "p1-portal-void",      text: "Hub Portal Void-Theme \u2705" },
    ],
  },
  {
    phase: "Phase 2 \u2013 Content & Polish",
    icon: "\uD83C\uDF0D",
    status: "planned",
    items: [
      { id: "p2-7-planets",       text: "Planeten 2-7 fuer Sonnensystem 1 (PM-009)" },
      { id: "p2-ore-textures",    text: "Erz-Typen & Texturen pro Planet" },
      { id: "p2-hub-ship",        text: "Hub/Raumschiff gestalten (PM-012)" },
      { id: "p2-npc-dialog",      text: "NPC-Dialog-System (PM-045)" },
      { id: "p2-npc-models",      text: "NPC-Modelle finalisieren (PM-046)" },
      { id: "p2-npc-ui",          text: "NPC-UI-Interaktionen (PM-047)" },
      { id: "p2-quest-nav",       text: "Smarte Quest-Navigation (PM-024)" },
      { id: "p2-mat-filter",      text: "Material-Liste filtern (PM-026)" },
      { id: "p2-automine-fx",     text: "Automine Effekte (PM-025)" },
      { id: "p2-auto-walk",       text: "Auto-Walk zum naechsten Erz (PM-057)" },
      { id: "p2-auto-mine",       text: "Auto-Mine Premium Feature (PM-058)" },
      { id: "p2-player-profile",  text: "Player Profile mit Stats (PM-059)" },
      { id: "p2-sound-fx-full",   text: "Sound FX komplett (PM-060)" },
      { id: "p2-dash",            text: "Dash-Mechanik (PM-029)" },
      { id: "p2-world-assets",    text: "Weltengestaltung mit Assets" },
    ],
  },
  {
    phase: "Phase 3 \u2013 Systems & Multiplayer",
    icon: "\u2728",
    status: "planned",
    items: [
      { id: "p3-player-limit",    text: "Multiplayer: Spielerlimit pro Planet" },
      { id: "p3-daily-quests",    text: "Taegliche Aufgaben System" },
      { id: "p3-solar-template",  text: "Sonnensystem-Template-System" },
    ],
  },
  {
    phase: "Phase 4 \u2013 Monetarisierung & Launch",
    icon: "\uD83D\uDCB0",
    status: "planned",
    items: [
      { id: "p4-cashshop",        text: "Cashshop mit Robux" },
      { id: "p4-premium-picks",   text: "Premium-Pickaxes" },
      { id: "p4-solar-2-3",       text: "Sonnensystem 2 & 3" },
      { id: "p4-marketing",       text: "Marketing & Community aufbauen" },
    ],
  },
  {
    phase: "Phase 5 \u2013 Community & Growth",
    icon: "\uD83D\uDE80",
    status: "planned",
    items: [
      { id: "p5-discord-bot",     text: "Discord Server + n8n Bot (Chat-Analyse, Stats)" },
      { id: "p5-wiki",            text: "Game Wiki mit Tutorials & Daten" },
      { id: "p5-social-content",  text: "YouTube + TikTok Content fuer Traffic" },
      { id: "p5-pets",            text: "Pet-System" },
      { id: "p5-localization",    text: "Lokalisierung (weitere Sprachen)" },
      { id: "p5-more-solar",      text: "Weitere Sonnensysteme nach Bedarf" },
      { id: "p5-events",          text: "Events & saisonale Inhalte" },
    ],
  },
];

// ============================================================
// SPIELERREISE
// ============================================================
const SPIELERREISE = {
  title: "Die Spielerreise",
  subtitle: "Was erlebt ein neuer Spieler von Minute 1 bis Endgame?",
  steps: [
    { time: "0\u20132 Min",   icon: "\uD83C\uDF1F", title: "Erster Kontakt",     desc: "Spawn auf Planet 1. Kleiner Planet, Stein ueberall. Tutorial zeigt: Klick = Abbauen. Sofort Drops & Feedback." },
    { time: "2\u201310 Min",  icon: "\u26CF\uFE0F",  title: "Erster Grind",       desc: "3 Stein-Groessen entdecken. Ziele erscheinen: 'Baue 50 Stein ab'. Erste Waehrung verdienen." },
    { time: "10\u201330 Min", icon: "\u2B06\uFE0F",  title: "Erster Upgrade",     desc: "Zum Hub fliegen. Materialien verkaufen. Erste Pickaxe-Upgrades kaufen. Unterschied spueren!" },
    { time: "30\u201360 Min", icon: "\uD83C\uDF1D",  title: "Planet 2",           desc: "Level 2 erreicht! Groesserer Planet, Kupfererz. Neue Farben, haertere Erze, mehr Drops." },
    { time: "1\u20135 Std",   icon: "\uD83C\uDF0D",  title: "Sonnensystem 1",     desc: "Planet fuer Planet durcharbeiten. Immer groesser, immer cooler. Leaderboard-Rankings steigen." },
    { time: "5+ Std",         icon: "\u2600\uFE0F",  title: "Neues Sonnensystem", desc: "Sonnensystem 2 freigeschaltet! Alles wird nochmal groesser und epischer." },
    { time: "Endgame",        icon: "\uD83C\uDF0C",  title: "Legende",            desc: "Top-Leaderboards, absurd grosse Planeten, beste Pickaxes. Taeglich wiederkommen fuer Daily Quests." },
  ],
};
